#pragma once
#include "Objects/BillBoard.h"
#include "Objects/Model.h"
#include "Objects/Plane.h"
#include "Objects/Sphere.h"
#include "Objects/Sprite.h"
#include "Objects/Tetrahedron.h"
#include "Objects/Triangle.h"
#include "Objects/WorldTransform.h"